name: Python Package CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9, "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Sanity check imports
      run: |
        python -c "import jax; import thrml; import panel; import plotly; import matplotlib; import networkx"

    - name: Run TSP demo script
      run: |
        if [ -f run_tsp_demo.py ]; then python run_tsp_demo.py; fi

    - name: List repo files
      run: ls -lh

    - name: (Optional) Panel dashboard test
      run: |
        echo "Test dashboard launch (not headless-browser tested)"
        if [ -f dashboard.py ]; then python -m panel serve dashboard.py --autoreload --show=False & sleep 10; fi

    - name: (Optional) Check Jupyter notebook
      run: |
        if [ -f demo.ipynb ]; then python -m nbconvert --execute --to notebook --inplace demo.ipynb; fi